Ext.define('DSN.model.system.Operator', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'optId',
        type: 'int'
    }, {
        name: 'optNo',
        type: 'string'
    }, {
        name: 'password',
        type: 'string'
    }, {
        name: 'optName',
        type: 'string'
    }, {
        name: 'gender',
        type: 'string'
    }, {
        name: 'status',
        type: 'string'
    }, {
        name: 'tel',
        type: 'string'
    }, {
        name: 'crtOptId',
        type: 'int'
    }, {
        name: 'crtTime',
        type: 'date'
    }, {
        name: 'userNo',
        type: 'string'
    }]
});